"""Added nn_client_firm2facility and reference in ClientFirm

Revision ID: cee34cc6ffb
Revises: None
Create Date: 2013-12-06 16:13:05.908769

"""

# revision identifiers, used by Alembic.
revision = 'cee34cc6ffb'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wiki_page',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('data', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('client_firm_facility',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('client',
    sa.Column('type', sa.CHAR(length=4), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label_name', sa.String(length=255), nullable=False),
    sa.Column('legal_title', sa.String(length=255), nullable=False),
    sa.Column('contacts', sa.String(length=255), nullable=True),
    sa.Column('bank_accounts', sa.String(length=255), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('passport', sa.String(length=255), nullable=True),
    sa.Column('INN', sa.Integer(), nullable=True),
    sa.Column('OGRN', sa.Integer(), nullable=True),
    sa.Column('KPP', sa.Integer(), nullable=True),
    sa.Column('legal_address', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('INN'),
    sa.UniqueConstraint('KPP'),
    sa.UniqueConstraint('OGRN'),
    sa.UniqueConstraint('label_name')
    )
    op.create_table('nn_client_firm2facility',
    sa.Column('client_firm_id', sa.Integer(), nullable=True),
    sa.Column('client_firm_facility_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_firm_facility_id'], ['client_firm_facility.id'], ),
    sa.ForeignKeyConstraint(['client_firm_id'], ['client.id'], ),
    sa.PrimaryKeyConstraint('client_firm_id', 'client_firm_facility_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nn_client_firm2facility')
    op.drop_table('client')
    op.drop_table('client_firm_facility')
    op.drop_table('wiki_page')
    ### end Alembic commands ###
